<?php
 $aik =  array (
  'sitename' => '小彬影院',
  'pcdomain' => 'index.php',
  'title' => '小彬影院-免VIP在线抢先观看最新好看的电影和电视剧',
  'keywords' => '小彬影院,电视直播网站,零八影院快播,高清云影视,云点播,免费看视频,湖南卫视直播,80电影网,最新电影天堂免费在线观看',
  'description' => '小彬影院,热剧快播,最好看的剧情片尽在﻿优奇艺影院,高清云影视免费为大家提供最新最全的免费电影，电视剧，综艺，动漫无广告在线云点播，以及电视直播',
  'homelink' => '<a href="http://dy.eb89.com" target="_blank"><font color="red">小彬影视</font></a>',
  'icp' => '粤ICP备15074943号',
  'foot' => '本站提供的最新电影和电视剧资源均系收集于各大视频网站,本站只提供web页面服务,并不提供影片资源存储,也不参与录制、上传</br>若本站收录的节目无意侵犯了贵司版权，请给网页底部邮箱地址来信,我们会及时处理和回复,谢谢。',
  'tongji' => '',
  'changyan' => '',
  'youlian' => '',
  'jiekou1' => 'http://j.zz22x.com/jx/?url=',
  'jiekou2' => 'http://api.xfsub.com/index.php?url=',
  'jiekou3' => 'http://api.baiyug.cn/vip/index.php?url=',
  'jiekou4' => 'http://jiexi.071811.cc/jx.php?url=',
  'jiekou5' => 'http://yun.mt2t.com/yun?url=',
  'jiekou6' => 'http://p2.api.47ks.com/webcloud/?v=',
  'jiekou7' => 'http://000o.cc/jx/ty.php?url=',
  'jiekou8' => 'http://jiexi.92fz.cn/player/vip.php?url=',
  'jiekou9' => 'https://api.flvsp.com/?url=',
  'jiekou10' => 'http://api.wlzhan.com/sudu/?url=',
  'admin_name' => 'admin',
  'admin_pass' => '68f077ad4e66c90c43752cda1a982e27',
  'admin_email' => '49553941@qq.com',
  'logo_dh' => '<img src=\\"images/logo.png \\">',
  'logo_ss' => '<img id=\\"imgsrc\\" src=\\"images/sologo.png\\"><p><center><iframe width=\\"280\\" scrolling=\\"no\\" height=\\"25\\" frameborder=\\"0\\" allowtransparency=\\"true\\" src=\\"http://i.tianqi.com/index.php?c=code&id=34&icon=1&num=3\\"></iframe></center>',
  'movie_ad' => '',
  'tv_ad' => '',
  'zongyi_ad' => '',
  'dongman_ad' => '',
  'bofang_ad' => '',
  'jiazai_ad' => '<a href=\\"http://wpa.qq.com/msgrd?v=3&uin=49553941&site=qq&menu=yes\\" target=\\"_blank\\"><img src=\\"images/jiazai.png\\" width=\\"100%\\"></a>',
  'dbts' => '【点击选择下面的剧集或名称才会播放哦！】',
  'zfb_ad' => '<img src=\\"images/fk.png\\">',
  'wx_ad' => '<img src=\\"images/fk.png\\">',
  'cebian1_ad' => '<a class=\\"style02\\" href=\\"\\" target=\\"_blank\\"><strong>在线观看</strong><div class=\\"article-wechats\\"> </br> <img src=\\"images/qrcode.jpg\\"></div> </a>',
  'cebian2_ad' => '<a class=\\"style02\\" href=\\"http://dy.eb89.com\\" target=\\"_blank\\"><strong>小彬影院</strong><h2>小彬影院-免VIP看视频</h2><p>小彬影院,热剧快播,最好看的剧情片,高清云影视免费为大家提供最新最全的免费电影，电视剧，综艺，动漫无广告在线云点播，以及电视直播。</p></a>',
  'cebian3_ad' => '<h3>免费在线观看</h3>			
<div class=\\"textwidget\\"><a href=\\"http://wpa.qq.com/msgrd?v=3&uin=49553941&site=qq&menu=yes\\" target=\\"_blank\\"><img src=\\"images/jianzhi.png\\" width=\\"100%\\"></a>',
  'cebian4_ad' => '<a class=\\"style01\\" href=\\"http://wpa.qq.com/msgrd?v=3&uin=49553941&site=qq&menu=yes\\" target=\\"_blank\\"><strong>公告信息：</strong><h2>免费在线观看最新电影电视</h2><p>1.更多精彩分享请收藏官方发布链接地址...<p>2.观看视频：点击视频的名称列表，再点击选择解析路线进行播放！提示：如解析线路播放有问题请选择其他线路，或者添加官方QQ交流群反馈</p></a></div>',
  'top1_ad' => '<a href=\\"zhibo.php\\">电视直播</a>',
  'top2_ad' => '<a href=\\"http://dy.eb89.com\\">官方发布</a>',
  'top_ad' => '<a href=\\"http://wpa.qq.com/msgrd?v=3&uin=49553941&site=qq&menu=yes\\">站长</a>',
  'weixin_ad' => '',
  'end_ad' => '',
  'hometopnotice' => '',
  'hometopright' => '',
  'sort' => '1,2,3,4,5,6,7,8,9,10',
  'joinhotkey' => '0',
);
?>